version: "3"

services:
  flexget:
    image: kmb32123/flexget-dockerfile
    environment:
      - TORRENT_PLUGIN=transmission
    volumes:
      - "./flexget:/flexget"
      - "./watch:/output"

  transmission:
    image: dperson/transmission
    # View the transmission_sample.env file for more instructions.
    env_file:
        - transmission.env
    ports:
      - "9991:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - "./transmission:/var/lib/transmission-daemon"
      - "./watch:/watch"
