version: "2"

services:
  flexget:
    image: monoetharyus/rpi-flexget
    entrypoint: /start.sh
    volumes:
      - "./flexget:/root/.flexget"
      - "./watch:/output"
    ports:
      - 5050:5050

  transmission:
    image: jaymoulin/transmission 
    environment:
        - USERNAME=username
        - PASSWORD=secretp4ssword
    ports:
      - "9991:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - "./transmission:/root/.config/transmission-daemon"
      - "./watch:/to_download"
      - "./output:/output"
